# src/main/resources/application.yml

server:
  port: ${PORT:8080}
  servlet:
    context-path: /education

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://education-khangdjnh24042002-3df5.c.aivencloud.com:25123/defaultdb?sslMode=REQUIRED&verifyServerCertificate=false}
    username: ${DB_USERNAME:avnadmin}
    password: ${DB_PASSWORD:AVNS_rsfDdzPtBTSJMGxYjEf}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://euc1.auth.ac/auth/realms/${idp.realm}}

  data:
    redis:
      url: ${REDIS_URL:rediss://default:AbBIAAIncDI5MmViNjgxYjUzYjY0N2JmYmY0N2Q4NzZkYjVjZTRlNXAyNDUxMjg@mint-jay-45128.upstash.io:6379}
      timeout: ${REDIS_TIMEOUT:5000ms}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:education.system042025@gmail.com}
    password: ${MAIL_PASSWORD:uoqn bmfq sslw paqt}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: ${MAIL_DEBUG:true}



# Custom properties
idp:
  url: ${KEYCLOAK_URL:https://euc1.auth.ac/auth}
  realm: ${KEYCLOAK_REALM:education-service}
  client-id: ${KEYCLOAK_CLIENT_ID:education_app}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:Tt6CGN0Sy5MK7VsFGl6qd860A04aiHhf}

cloud:
  r2:
    endpoint: ${R2_ENDPOINT:https://499ff9f796f74256796a481346726f6e.r2.cloudflarestorage.com}
    access-key: ${R2_ACCESS_KEY:caaaf6f80bd0ca0fe384aa256a0b25a3}
    secret-key: ${R2_SECRET_KEY:d34955c37c61fb506137d85e1e0173b551e81f87b1033dadd4f2c360e2b1aeea}
    bucket: ${R2_BUCKET:e-learning}
    region: ${R2_REGION:auto}

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

logging:
  level:
    org.springframework.security: ${LOG_SECURITY:DEBUG}
    org.springframework.web: ${LOG_WEB:DEBUG}