server:
    port: 8080
    servlet:
        context-path: /education

spring:
    datasource:
        url: jdbc:mysql://localhost:3307/education_system
        username: root
        password: root

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8180/realms/education-service

    doc:
        swagger-ui:
            path: /swagger-ui/index.html

    mail:
        host: smtp.gmail.com
        port: 587
        username: education.system042025@gmail.com
        password: "uoqn bmfq sslw paqt"
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000
        debug: true

    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 20MB

    data:
        redis:
            host: localhost
            port: 6379
            timeout: 5000

file:
    upload-dir: uploads/assignments/

idp:
    url: http://localhost:8180
    client-id: education_app
    client-secret: VzYF8s3JFejTwDFTE0df2GH5YuF4AXNA

logging:
    level:
        org.springframework.security: DEBUG
        org.springframework.web: DEBUG

cloud:
    r2:
        endpoint: https://499ff9f796f74256796a481346726f6e.r2.cloudflarestorage.com
        access-key: caaaf6f80bd0ca0fe384aa256a0b25a3
        secret-key: d34955c37c61fb506137d85e1e0173b551e81f87b1033dadd4f2c360e2b1aeea
        bucket: e-learning
        region: auto
